
import { MutualFund, UserRole } from './types';

export const USER_ROLES: UserRole[] = [
  UserRole.Investor,
  UserRole.FinancialAdvisor,
  UserRole.DataAnalyst,
  UserRole.Admin,
];

export const MUTUAL_FUNDS: MutualFund[] = [
  {
    id: 'tech-growth-01',
    name: 'Innovate Tech Growth Fund',
    category: 'Technology Equity',
    description: 'A fund focused on high-growth potential technology companies, including software, hardware, and emerging tech sectors.',
    nav: 154.25,
    aum: '1.2B',
    expenseRatio: 0.85,
    riskLevel: 'High',
    oneYearReturn: 25.4,
    holdings: [
      { name: 'Alpha Solutions Inc.', percentage: 8.5 },
      { name: 'NextGen AI Corp.', percentage: 7.2 },
      { name: 'Quantum Computing Co.', percentage: 6.8 },
      { name: 'DataStream Analytics', percentage: 5.5 },
      { name: 'CyberSecure Ltd.', percentage: 5.1 },
      { name: 'CloudNet Services', percentage: 4.9 },
      { name: 'BioSynth Robotics', percentage: 4.3 },
      { name: 'Fusion Energy', percentage: 3.9 },
      { name: 'Virtual Realities Inc.', percentage: 3.5 },
      { name: 'ConnectSphere', percentage: 3.2 },
    ],
    performance: [
      { month: 'Jan', nav: 120 }, { month: 'Feb', nav: 125 }, { month: 'Mar', nav: 122 },
      { month: 'Apr', nav: 130 }, { month: 'May', nav: 135 }, { month: 'Jun', nav: 140 },
      { month: 'Jul', nav: 142 }, { month: 'Aug', nav: 148 }, { month: 'Sep', nav: 145 },
      { month: 'Oct', nav: 150 }, { month: 'Nov', nav: 155 }, { month: 'Dec', nav: 154.25 },
    ],
  },
  {
    id: 'stable-income-02',
    name: 'Global Stable Income Fund',
    category: 'Corporate Bond',
    description: 'Invests in a diversified portfolio of high-quality corporate bonds from around the world to provide a stable stream of income.',
    nav: 98.6,
    aum: '3.5B',
    expenseRatio: 0.45,
    riskLevel: 'Low',
    oneYearReturn: 5.8,
    holdings: [
      { name: 'Global Bank Corp Bond', percentage: 9.1 },
      { name: 'Sturdy Industries Bond', percentage: 8.4 },
      { name: 'Pioneer Utilities Debt', percentage: 7.5 },
      { name: 'BlueChip Telecom Bond', percentage: 6.8 },
      { name: 'HealthCare Giants Debt', percentage: 6.2 },
      { name: 'Consumer Staples Co.', percentage: 5.5 },
      { name: 'Logistics Leaders Bond', percentage: 5.0 },
      { name: 'Prime Real Estate Debt', percentage: 4.5 },
      { name: 'Infrastructure Invest', percentage: 4.1 },
      { name: 'National Rail Bonds', percentage: 3.8 },
    ],
    performance: [
      { month: 'Jan', nav: 95 }, { month: 'Feb', nav: 95.5 }, { month: 'Mar', nav: 96 },
      { month: 'Apr', nav: 96.2 }, { month: 'May', nav: 96.8 }, { month: 'Jun', nav: 97 },
      { month: 'Jul', nav: 97.5 }, { month: 'Aug', nav: 98 }, { month: 'Sep', nav: 98.2 },
      { month: 'Oct', nav: 98.4 }, { month: 'Nov', nav: 98.5 }, { month: 'Dec', nav: 98.6 },
    ],
  },
  {
    id: 'eco-sustain-03',
    name: 'Eco Sustain World Fund',
    category: 'ESG Equity',
    description: 'Focuses on companies that demonstrate strong Environmental, Social, and Governance (ESG) practices for long-term sustainable growth.',
    nav: 121.75,
    aum: '850M',
    expenseRatio: 0.72,
    riskLevel: 'Medium',
    oneYearReturn: 15.2,
    holdings: [
      { name: 'GreenEnergy Solutions', percentage: 9.8 },
      { name: 'CleanWater Tech', percentage: 8.5 },
      { name: 'Sustainable Agriculture Inc.', percentage: 7.9 },
      { name: 'Ethical Pharma Co.', percentage: 6.5 },
      { name: 'Recycle Innovations', percentage: 6.0 },
      { name: 'Community Bank Corp.', percentage: 5.4 },
      { name: 'FairTrade Goods', percentage: 4.8 },
      { name: 'Education For All', percentage: 4.2 },
      { name: 'Efficient Homes Inc.', percentage: 3.9 },
      { name: 'Future Mobility', percentage: 3.5 },
    ],
    performance: [
      { month: 'Jan', nav: 105 }, { month: 'Feb', nav: 108 }, { month: 'Mar', nav: 106 },
      { month: 'Apr', nav: 110 }, { month: 'May', nav: 112 }, { month: 'Jun', nav: 115 },
      { month: 'Jul', nav: 118 }, { month: 'Aug', nav: 120 }, { month: 'Sep', nav: 117 },
      { month: 'Oct', nav: 119 }, { month: 'Nov', nav: 122 }, { month: 'Dec', nav: 121.75 },
    ],
  },
];
